### ISSUE TITLE
Package not installing properly

### ISSUE THREAD

**Issue by lopis** [probablyup/markdown-to-jsx#104]
I think there is something wrong when installing `markdown-to-jsx`. Maybe I'm missing something, but all I get is this:

![image](https://cloud.githubusercontent.com/assets/2715751/25472798/22bc39b0-2b2d-11e7-859d-10c9e54b02c5.png)

I'm only using this package as a dependency of https://github.com/styleguidist/react-styleguidist
I was expecting to find the main file `index.es5.js` in the node_modules directory but all I found is what you see in the picture above.

I'm on react 15.5.0, Ubuntu 16.04

**Comment by n1313** [comment]
Yep, index.es5.js is missing in v5.3.0. Rolling back to v5.2.0 fixes the problem.

**Comment by bstream** [comment]
My guess is that the culprit is `prepublishOnly` (fafab4210f817ac9b727b9e9c602cbc25a95fc48). According to http://blog.lholmquist.org/npm-prepublish-changes/ you need to run `npm@4.x` to run that script. 

I had great success with using https://github.com/iarna/in-publish for the same use case before.

**Comment by karatechops** [comment]
Ran into this issue today on our servers running [Grommet](https://github.com/grommet/grommet). Yarn seems to resolve the issue for the time being.

**Comment by probablyup** [comment]
5.3.2 has the fix from @bstream

**Comment by sapegin** [comment]
@probablyup Awesome, thanks!
