### ISSUE TITLE
html comment causes "Error: Invalid tag: --"

### ISSUE THREAD

**Issue by bguiz** [probablyup/markdown-to-jsx#110]
When parsing the following markdown:

```
foo

<!-- comment -->

bar
```

The generated JSX fails to render, with the error: `Error: Invalid tag: --` (an Invariant Violation in within React). Removing the HTML comment (`<!-- comment -->`) makes this go away, but it really should be allowed.

**Comment by probablyup** [comment]
This is likely a remark thing (the parsing engine I use under the hood.) If
so, there's not much I can do.

React also can't create comments via React.createElement as far as I know
(see https://github.com/facebook/react/issues/2810). Could maybe throw them
out?

**Comment by bguiz** [comment]
Yeah, discarding the HTML comments is fine - and in fact that's what I think should be the expected behaviour.

In fact, I attempted to use the `overrides` option to accomplish this, but was not able to figure out how.

**Comment by probablyup** [comment]
Overrides don't apply for unparseable HTML since it goes through the `dangerouslySetInnerHTML` escape hatch and skips the rest of the pipeline. Not the best experience, but it'll have to do for the moment.

I opened up an issue on remark to see if Titus wants to build in first-party support. If not I'll try and work up some sort of regex parsing to drop it. It's a little complicated though because any text around the comment on the same line gets lumped in, so if we simply drop the comment block the text would go too.

**Comment by bguiz** [comment]
That sounds like a good plan. 

As far as I am concerned the limitation around stuff surrounding the HTML comment also getting dropped is a non-issue, because I always have them on their own lines.
In fact, I also surround it using empty lines as well,
because some markdown parsers require any HTML tags to do that in order to be treated as HTML instead of markdown.

However, I'm cognizant that not everyone else does the same, so if it is possible, the regex could be used to parse and replace with an empty string rather than drop the line instead. I'm not sure of the internals, so I'm not sure if implementing that is feasible. If it is however, it would break things for less people!

**Comment by probablyup** [comment]
https://github.com/probablyup/markdown-to-jsx/releases/tag/5.4.1 should fix it. Thanks for reporting!
