### ISSUE TITLE
code blocks with highlight.js support !!

### ISSUE THREAD

**Issue by yjose** [probablyup/markdown-to-jsx#143]
Hi thank you for your amazing work !

I have just try to use this lib to render markdown but my jsx code block inside my markdown is rendered without highlight.

it will work out of the box or I need some kind of configurations ??

**Comment by probablyup** [comment]
Hey there! You just need to set up
https://www.npmjs.com/package/highlight.js in your project.

**Comment by probablyup** [comment]
Did a quick look around and it doesn’t look like ther are many examples, weirdly. My recommendation would be to load the highlight library and call its highlighting function on componentDidMount and componentDidUpdate for your container component.

**Comment by yjose** [comment]
Hi Evan
As you already mentioned to add highlight library I need to call the highlighting function on componentDidMount, it's work fine but for me, i need to highlight my code in the build time and not in the browser rendering. Not only that, the highlight library doesn't support enough libs code highlighting (jsx for example).

so, to solve my problem I suggest adding prismjs support to markdown-to-jsx. 
let's take a look at my implementation inspired by the Gatsby implementation for prismjs highlighting and let's me know your remarks and if it's worth more work for a pull request.

https://github.com/yjose/markdown-to-jsx/commit/f07a5c67aa02bde5a0d19142a3836bd25efd4570

**Comment by probablyup** [comment]
So I wouldn’t want to pull in prism in this project, but we could certainly also output prism-compatible classes.

**Comment by hugmanrique** [comment]
I'm looking for something like @yjose 's PR because I'm trying to render markdown on the server-side (by calling the `compiler()` func), and an option for overriding the `react` function of each component type would be great ([Example](https://github.com/yjose/markdown-to-jsx/blob/f07a5c67aa02bde5a0d19142a3836bd25efd4570/index.js#L651)). I've tried to create an override for it (tried both `codeBlock` and `pre`) and obviously it expects a React component, not a plain function.

**Comment by luvwinnie** [comment]
I have found out the way to highlight, the `hljs.initHighlighting();` should be called on componentDidUpdate() . I think maybe add an example could help out other people!
