### ISSUE TITLE
List won´t render with preceding text

### ISSUE THREAD

**Issue by Rall3n** [probablyup/markdown-to-jsx#217]
Version: `6.7.4`

If a list is being preceded by a paragraph, then the list won´t render normally. If there is at least one empty new line between them, the list will render.

This will render normally:
```markdown
[Markdown](http://daringfireball.net/projects/markdown/) lets you write content in a really natural way.

  * You can have lists, like this one
  * Make things **bold** or *italic*
  * Embed snippets of `code`
  * Create [links](/)
  * ...
```

But this won´t render the list:
```markdown
[Markdown](http://daringfireball.net/projects/markdown/) lets you write content in a really natural way.
  * You can have lists, like this one
  * Make things **bold** or *italic*
  * Embed snippets of `code`
  * Create [links](/)
  * ...
```

**Comment by probablyup** [comment]
Hey there - you need a newline between to denote that the first line is a separate paragraph per the markdown spec: https://daringfireball.net/projects/markdown/syntax#p

**Comment by dendrochronology** [comment]
Sorry for kicking a dead issue, but I just bumped into this as well. I know what the spec says, but neither commonmark nor GFM require an empty line. Since all the cool kids wanna do what Github does, I'm starting to see this out in the wild more, sometimes from systems I don't control.

Since you've already forked simple-markdown, maybe this could be an optional render flag or something? That would prevent the need to preprocess.
