### ISSUE TITLE
Question: Does markdown-to-jsx/dist/esm.js file have an issue when minified? 

### ISSUE THREAD

**Issue by NishantShenoy** [probablyup/markdown-to-jsx#224]
Hi I'm using react-styleguidist which uses markdown-to-jsx to render the markdown files. I started getting an error in the console which says: `Uncaught ReferenceError: returntrue is not defined`  on opening the dev tools it looks like there is an issue here: 
![image](https://user-images.githubusercontent.com/15218556/47324320-24ce7400-d614-11e8-8e7c-106ee7d72287.png)

Is this an open issue? 

Here's the version:
`  "markdown-to-jsx": {
            "version": "6.8.1",
            "resolved": "resolved url",
            "integrity": "SHA token",
            "dev": true,
            "requires": {
                "prop-types": "^15.6.2",
                "unquote": "^1.1.0"
            }
        },`

Thank you in advance for taking the time to look at this. Apologize in advance if I haven't followed a bug opening template. I'd be more than happy to reopen this in the correct template.

Regards,
Nishant

**Comment by probablyup** [comment]
Hmm I just started using Babel minify, maybe there's a bug in the minifier?

**Comment by NishantShenoy** [comment]
Here you go : https://github.com/styleguidist/react-styleguidist/issues/1181 . Maybe it's an issue with the UglifyJSPlugin 😄  thank you! closing this.

**Comment by probablyup** [comment]
Ah I see. So in esm.js the relevant code is:

```
return'production'!==process.env.NODE_ENV
```

And the bundler is likely replacing `process.env.NODE_ENV` with `'development'`.

And then perhaps the minifier is running a second time and since `'production' !== 'development'` is `true`, it's replacing it without adding a necessary space back?

**Comment by NishantShenoy** [comment]
That sounds right, but UglifyJS hasn't had an any change made to it although webpack has. I haven't had the change to look into it closely.

**Comment by diegohaz** [comment]
I'm also getting this error after upgrading this library.

**Comment by probablyup** [comment]
I think this plugin needs to be disabled from the preset:
https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-flip-comparisons

**Comment by eemeli** [comment]
@NishantShenoy The issue is probably not directly with UglifyJSPlugin, as it's present also in version 8.0.0 of Styleguidist, which [uses](/styleguidist/react-styleguidist/compare/v7.3.11...v8.0.0) TerserPlugin instead.

I'm not sure what the original source of this problem is, but as pinning markdown-to-jsx to 6.7.4 fixed it for me, I'd recommend re-opening this issue.

**Comment by a-type** [comment]
Hello, found this from Styleguidist. I believe the problem here is that, in the minified source, there is a statement `return'production'==process.env.NODE_ENV`, which is interpolated (I think by Webpack) into `returntrue` or `returnfalse` (the equality check here is being replaced inline with its static evaluation).

This seems to be combination of placing the string at the start of the conditional, and removing spaces wherever possible.

**Comment by probablyup** [comment]
Try 6.8.2

**Comment by ryanfitzer** [comment]
Just in time! Ran into this last night. @probablyup Thanks for the quick turnaround.
