### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [probablyup/markdown-to-jsx#351]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by probablyup** [comment]
If it’s a ReDOS thing I don’t care, thanks.


On November 30, 2020 at 9:21:24 AM, Alvaro Muñoz (notifications@github.com)
wrote:

Hello,

The GitHub Security Lab team <https://securitylab.github.com/> has found a
potential vulnerability in your project. Please create a Security Advisory
<https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory>
and invite me in to further disclose and discuss the vulnerability details
and potential fix. Alternatively, please add a Security Policy
<https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository>
containing a security email address to send the details to.

Kind regards,
A

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/probablyup/markdown-to-jsx/issues/351>, or unsubscribe

**Comment by pwntester** [comment]
Ok, thanks
